### ISSUE TITLE
Get RTL-SDR tuning NWR

### ISSUE THREAD

**Issue by ke4roh** [ke4roh/RPiNWR#26]
I have received various instructions such as this:
http://www.instructables.com/id/RTL-SDR-FM-radio-receiver-with-GNU-Radio-Companion/

for tuning NWR via RTL-SDR.  The challenge is not so much receiving FM as getting the darn thing to work.  I'm running Fedora 24 on my laptop, and the waterfall displays don't work, erroring out (see log in comments) and I hear static on the radio.  So I'm misunderstanding something and/or have things installed incorrectly, but my Google-fu is tapped out.

**Comment by ke4roh** [comment]
Here's an example of the errors I'm getting:

```
Generating: '/home/jscarbor/tmp/sdr/top_block.py'

Executing: /usr/bin/python2 -u /home/jscarbor/tmp/sdr/top_block.py

linux; GNU C++ version 6.1.1 20160510 (Red Hat 6.1.1-2); Boost_106000; UHD_003.009.004-0-unknown

gr-osmosdr v0.1.x (0.1.4git) gnuradio 3.7.10.1
built-in source types: file fcd rtl rtl_tcp uhd hackrf rfspace 
Using device #0 Realtek RTL2838UHIDIR SN: 00000001
Found Rafael Micro R820T tuner
Invalid sample rate: 100000 Hz
INFO: Audio sink arch: alsa
len(audio_taps) = 115
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/gnuradio/wxgui/plotter/plotter_base.py", line 209, in _on_paint
    for fcn in self._draw_fcns: fcn[1]()
  File "/usr/lib64/python2.7/site-packages/gnuradio/wxgui/plotter/plotter_base.py", line 61, in draw
    self._draw()
  File "/usr/lib64/python2.7/site-packages/gnuradio/wxgui/plotter/grid_plotter_base.py", line 239, in _draw_grid
    for tick in self._get_ticks(self.x_min, self.x_max, self.x_step, self.x_scalar)]
  File "/usr/lib64/python2.7/site-packages/gnuradio/wxgui/plotter/grid_plotter_base.py", line 341, in _get_tick_label
    return gltext.Text(tick_str, font_size=TICK_TEXT_FONT_SIZE)
  File "/usr/lib64/python2.7/site-packages/gnuradio/wxgui/plotter/gltext.py", line 344, in __init__
    self._initText()
  File "/usr/lib64/python2.7/site-packages/gnuradio/wxgui/plotter/gltext.py", line 380, in _initText
    self._centered)
  File "/usr/lib64/python2.7/site-packages/gnuradio/wxgui/plotter/gltext.py", line 73, in __init__
    self.createTexture()
  File "/usr/lib64/python2.7/site-packages/gnuradio/wxgui/plotter/gltext.py", line 233, in createTexture
    self._texture = glGenTextures(1)
  File "latebind.pyx", line 32, in OpenGL_accelerate.latebind.LateBind.__call__ (src/latebind.c:989)
  File "wrapper.pyx", line 303, in OpenGL_accelerate.wrapper.Wrapper.__call__ (src/wrapper.c:6338)
  File "wrapper.pyx", line 88, in OpenGL_accelerate.wrapper.CArgCalculator.c_call (src/wrapper.c:2984)
  File "wrapper.pyx", line 69, in OpenGL_accelerate.wrapper.CArgCalculatorElement.c_call (src/wrapper.c:2536)
  File "wrapper.pyx", line 64, in OpenGL_accelerate.wrapper.CArgCalculatorElement.c_call (src/wrapper.c:2422)
  File "arraydatatype.pyx", line 357, in OpenGL_accelerate.arraydatatype.SizedOutputOrInput.c_call (src/arraydatatype.c:7335)
  File "arraydatatype.pyx", line 226, in OpenGL_accelerate.arraydatatype.ArrayDatatype.c_zeros (src/arraydatatype.c:5090)
  File "arraydatatype.pyx", line 71, in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_get_output_handler (src/arraydatatype.c:2407)
  File "arraydatatype.pyx", line 82, in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_handler_by_plugin_name (src/arraydatatype.c:2579)
  File "/usr/lib/python2.7/site-packages/OpenGL/plugins.py", line 16, in load
    return importByName( self.import_path )
  File "/usr/lib/python2.7/site-packages/OpenGL/plugins.py", line 38, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/usr/lib/python2.7/site-packages/OpenGL/arrays/numpymodule.py", line 27, in <module>
    from OpenGL_accelerate.numpy_formathandler import NumpyHandler
  File "__init__.pxd", line 155, in init OpenGL_accelerate.numpy_formathandler (src/numpy_formathandler.c:5845)
ValueError: ('numpy.dtype has the wrong size, try recompiling', 1, <OpenGL.platform.baseplatform.glGenTextures object at 0x7efd204846e0>)
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOcb transfer status: 5, canceling...
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
rtlsdr_read_async returned with -5
```
