### ISSUE TITLE
GPIO startup sometimes fails

### ISSUE THREAD

**Issue by ke4roh** [ke4roh/RPiNWR#3]
This happens primarily after abnormal program termination.  Manual recovery is possible suggesting automated recovery might also be possible.  See also issue #2.

```
2016-04-21 16:59:11,156 queue processing failed                                                                    
Traceback (most recent call last):                                                                                 
  File "/home/pi/test/RPiNWR/Si4707/__init__.py", line 74, in __command_loop                                       
    status = self.check_interrupts()                                                                               
  File "/home/pi/test/RPiNWR/Si4707/__init__.py", line 205, in check_interrupts                                    
    self.wait_for_clear_to_send(timeout=5)                                                                         
  File "/home/pi/test/RPiNWR/Si4707/__init__.py", line 184, in wait_for_clear_to_send                              
    self.status = Status(self.hardware_io.readList(0, 1))                                                          
  File "/usr/local/lib/python3.4/dist-packages/Adafruit_GPIO-0.9.3-py3.4.egg/Adafruit_GPIO/I2C.py", line 129, in re
adList                                                                                                             
    results = self._bus.read_i2c_block_data(self._address, register, length)                                       
OSError: [Errno 5] Input/output error                                                                              
2016-04-21 16:59:11,158 I/O error                                                                                  
2016-04-21 16:59:11,158 I/O error                                                                                  
Traceback (most recent call last):                                                                                 
  File "/home/pi/test/RPiNWR/Si4707/__init__.py", line 184, in wait_for_clear_to_send                              
    self.status = Status(self.hardware_io.readList(0, 1))                                                          
  File "/usr/local/lib/python3.4/dist-packages/Adafruit_GPIO-0.9.3-py3.4.egg/Adafruit_GPIO/I2C.py", line 129, in readList                                                                                                             
    results = self._bus.read_i2c_block_data(self._address, register, length)                                       
OSError: [Errno 5] Input/output error
2016-04-21 16:59:11,156 queue processing failed                                                                    
Traceback (most recent call last):                                                                                 
  File "/home/pi/test/RPiNWR/Si4707/__init__.py", line 74, in __command_loop                                       
    status = self.check_interrupts()                                                                               
  File "/home/pi/test/RPiNWR/Si4707/__init__.py", line 205, in check_interrupts                                    
    self.wait_for_clear_to_send(timeout=5)                                                                         
  File "/home/pi/test/RPiNWR/Si4707/__init__.py", line 184, in wait_for_clear_to_send                              
    self.status = Status(self.hardware_io.readList(0, 1))                                                          
  File "/usr/local/lib/python3.4/dist-packages/Adafruit_GPIO-0.9.3-py3.4.egg/Adafruit_GPIO/I2C.py", line 129, in readList                                                                                                             
    results = self._bus.read_i2c_block_data(self._address, register, length)                                       
OSError: [Errno 5] Input/output error                                                                              
2016-04-21 16:59:11,158 I/O error                                                                                  
2016-04-21 16:59:11,158 I/O error                                                                                  
Traceback (most recent call last):                                                                                 
  File "/home/pi/test/RPiNWR/Si4707/__init__.py", line 184, in wait_for_clear_to_send                              
    self.status = Status(self.hardware_io.readList(0, 1))                                                          
  File "/usr/local/lib/python3.4/dist-packages/Adafruit_GPIO-0.9.3-py3.4.egg/Adafruit_GPIO/I2C.py", line 129, in readList                                                                                                             
    results = self._bus.read_i2c_block_data(self._address, register, length)           
SError: [Errno 5] Input/output error                                                                              
2016-04-21 16:59:11,159 Startup failed                                                                             
Traceback (most recent call last):                                                                                 
  File "/home/pi/test/RPiNWR/Si4707/__init__.py", line 62, in __enter__                                            
    self.wait_for_clear_to_send(timeout=5)                                                                         
  File "/home/pi/test/RPiNWR/Si4707/__init__.py", line 184, in wait_for_clear_to_send                              
    self.status = Status(self.hardware_io.readList(0, 1))                                                          
  File "/usr/local/lib/python3.4/dist-packages/Adafruit_GPIO-0.9.3-py3.4.egg/Adafruit_GPIO/I2C.py", line 129, in readList                                                                                                             
    results = self._bus.read_i2c_block_data(self._address, register, length)                                       
OSError: [Errno 5] Input/output error            
```

**Comment by ke4roh** [comment]
Resolved with a GPIO reset if there's an IO error after the first attempt.  

https://github.com/ke4roh/RPiNWR/commit/d7a7ee885c7ec6980c905f32766f29b7178be64f
