### ISSUE TITLE
Exception in radio.log after EOM

### ISSUE THREAD

**Issue by ke4roh** [ke4roh/RPiNWR#5]
```
2016-05-12 19:09:15,880 INFO  SetProperty [time_complete: 1463094555.8747818, future: None, value: 18, property: Property [value: 3, code: 16385, validator: <function <lambda> at 0x768740c0>, mnemonic: RX_HARD_MUTE], exception: None, _logger: <logging.Logger object at 0x767aa4b0>, result: None, valid_values: 18, mnemonic: SET_PROPERTY]
2016-05-12 19:09:17,261 DEBUG Read the following from register 0x00: [132]
2016-05-12 19:09:17,263 DEBUG Wrote to register 0x54: [1, 0]
2016-05-12 19:09:17,267 DEBUG Read the following from register 0x00: [128, 10, 0, 0, 0, 0, 255, 255, 0, 255, 255, 255, 255, 255]
2016-05-12 19:09:17,268 ERROR failed
Traceback (most recent call last):
  File "/home/pi/test/RPiNWR/Si4707/commands.py", line 57, in do_command
    result = self.do_command0(radio)
  File "/home/pi/test/RPiNWR/Si4707/commands.py", line 391, in do_command0
    radio.same_message.extend_timeout()
  File "/home/pi/test/RPiNWR/SAME.py", line 279, in extend_timeout
    raise ValueError("Message is already complete.")
ValueError: Message is already complete.
2016-05-12 19:09:17,270 DEBUG Executed SameInterruptCheck [EOMDET PREDET intack len = 0 state = 0 m=[255, 255, 0, 255, 255, 255, 255, 255] ]
2016-05-12 19:09:17,274 DEBUG Wrote to register 0x54: [2, 0]
2016-05-12 19:09:17,275 INFO  CommandExceptionEvent [passed_back: True, exception: Message is already complete., time: 1463094557.2706087]
2016-05-12 19:09:17,276 DEBUG Read the following from register 0x00: [0]
2016-05-12 19:09:17,275 INFO  CommandExceptionEvent [passed_back: True, exception: Message is already complete., time: 1463094557.2706087]
```

**Comment by ke4roh** [comment]
No exception with today's RWT.  Waiting for a storm system to pass through without exceptions before closing the issue.
